### ISSUE TITLE
Going back from zoom causes history loop

### ISSUE THREAD

**Issue by bliker** [SlovakNationalGallery/web-umenia-2#1]
When going into zoom and clicking **NASPÄŤ** the history becomes looped due to [funky](http://stackoverflow.com/questions/26992109/urlprevious-issue-in-laravel) `Url::Previous` behaviour.

Could be solved by swapping [relevant line](https://github.com/SlovakNationalGallery/web-umenia-2/blob/3ad960011803f88b7e7e970578337e60598513d5/app/views/zoom.blade.php#L70) with JS history call.

**Comment by igor-kamil** [comment]
thank you @bliker for reporting
fixed with 3a8f430decbd567ca07fbb4e2c567f483aef1d85
good point! ;)
