### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by smiklosovic** [SlovakNationalGallery/web-umenia-2#19]
Hey guys, @igor-kamil , @phillchill 

I was at ArtData hackaton and I liked it a lot!

I was thinking if there is any will to put this whole web thing into Docker so running the web would be total no-brainer. I am actually for Docker compose approach where in one Docker container you would have just web itself and in another one there would be configured ElasticSearch running so end-user (developer) of this is not required to configure nothing at all.

Source code of the web would be mounted to Docker container so you could develop the web as you are used and you would just create a container from an image.

We could put the images to public https://hub.docker.com/.

**Comment by phillchill** [comment]
Hey @smiklosovic , thanks for your suggestion and sorry for not replying earlier!

I think Docker would be a great way to lower the barrier for new developers to try out Webumenia. @igor-kamil and I see the benefits, but for the moment we aren't planning to invest time into setting it up. That said, @igor-kamil is trying out Docker on another project, which should give some useful experience that will inform a decision further down the line.

When that moment is there we'll definitely let you know. In the mean time if there's anyway we can do to help you get things going, please keep in touch!

**Comment by phivk** [comment]
Hi @smiklosovic !
I'm convinced Docker (+ Compose) can provide a great way to get people started developing. I'd like to look into using it with Web umenia (atm I'm a complete beginner).

Do you have experience with setting up a Docker Compose project?
Would you like to help out to set it up for Web umenia?

**Comment by phivk** [comment]
@xar that would be awesome!
Have you managed to get everything running so far?
Is there anything that was unclear or challenging in the process?

**Comment by phivk** [comment]
@xar did you get a chance to give this a try?
Anything I can do to support?

**Comment by xar** [comment]
Hey @phivk, actually I create base Dockerfile + docker-compose.yaml in my fork. Didn't had much more time to finish up :/

**Comment by Endut** [comment]
@xar I'm going to be looking at dockerizing web-umenia in the next few weeks a little bit more intensively, would you mind sharing your experiences with this, or any problems you found?

**Comment by Endut** [comment]
@xar https://github.com/SlovakNationalGallery/web-umenia-2/tree/feature%2Fdockerize-web-umenia this is more or less working for me
