### ISSUE TITLE
Remove sensitive information from UserSeeded

### ISSUE THREAD

**Issue by stanogurnik** [SlovakNationalGallery/web-umenia-2#2]
Remove passwords from User seeder, you are publicly exposing sensitive data and let users to change their crendentials asap. `press` & `sng` access is still working on production app.

**Comment by igor-kamil** [comment]
thank you for notifying
passwords in UserSeeder were supposed to be just placeholders
however - it's quite awkward they stayed on production :P

fixed immediately
