### ISSUE TITLE
issue tracker

### ISSUE THREAD

**Issue by xar** [SlovakNationalGallery/web-umenia-2#20]
ahoj, existuje nejaky verejny issue tracker? Ak by som sa chcel zapojit na com by som mohol pracovat?

**Comment by phivk** [comment]
Hi @xar !
Thanks for the suggestion and sorry for the late reply 😊  ...

We are currently working on making it easier for external people to contribute, which will include setting up a public issue tracker 🎉 
We are currently upgrading our internal issue tracker (by Atlassian) to the shiny new version and will use it to create public milestones and issues.

For now I can share that we are looking for contributions in the following areas:

- Making it stupidly simply to get started developing Web umenia on your own
- Getting more content like articles and collections in English
- Making the entire platform accessible in Slovak, English and Czech
- Creating a ‘living pattern library’ to document our modular front-end design and make it easy to maintain and customise.

Is there any of those that sound interesting to you?

**Comment by phivk** [comment]
We are currently happily using the issues section here on GitHub for public issues. 
Please keep submitting issues here. We have also added several issues ourselves that might provide a nice starting point for contributors.
Closing this issue...
